### ISSUE TITLE
Kamailio does not start

### ISSUE THREAD

**Issue by atuxnull** [os11k/dispatcher#1] opened 2020-07-20 07:45 UTC
Hi. I am trying to setup a dispatcher to my 2 Asterisk boxes (192.168.1.232 & 192.168.1.233). Kamailio has the IP 192.168.1.218. I did install Kamailio from deb repo (5.3) and it is up and running. 4 extensions (101, 102, 103, 104) have been created and can talk to each other.
I am looking for Kamailio to have all the registrations and forward the media services to the Asterisk boxes.
Once i did the changes of kamailio.cfg and added the dispatcher.list, kamailio does not start and journactl -xe shows the following errors: [errors.txt](https://github.com/os11k/dispatcher/files/4946212/errors.txt)

The following 2 are the kamailio.cfg and dispatcher.list
[dispatcher.list.txt](https://github.com/os11k/dispatcher/files/4946195/dispatcher.list.txt)
[kamailio.cfg.txt](https://github.com/os11k/dispatcher/files/4946196/kamailio.cfg.txt)

In each Asterisk box i have in sip.conf 
```
[kamailio]
host=192.168.1.218
port=5060
insecure=invite
type=friend
context=from-pstn
```

i would appreciate any help available to fix the issue, please.

**Comment by os11k** [comment] 2020-07-20 08:09
Hi,

Check this part of error:

`Jul 20 10:41:14 debian kamailio[994]: CRITICAL: <core> [core/cfg.y:3543]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 256, column 12-26: failed to load module
Jul 20 10:41:14 debian kamailio[994]: ERROR: bad config file (1 errors)`

Seems on line 256 you have double entries of `loadmodule "dispatcher.so"` or just module is not there and you still need path module too, without it will not work. I would recommend for beginning to try to run kamailio with my confg file, before running your own file. Additionally route[REGISTRAR] is totally incorrect and it will not work in such way.

**Comment by atuxnull** [comment] 2020-07-20 14:48
Thanks for the reply. It is fixed and Kamailio starts.
I have a question though if you cou ld help me. I have created the dispatch.list with the 2 IPs of the Asterisk boxes. They are identical and i have created on the sip.conf a user. Asterisk bind port is on 5080, while Kamailio is on 5060. On the Asterisk i see that Kamailio is reachable.
On the Kamailio i am creating the same user as in Asterisk (500). Then on the phone i am trying to register user 500 with the ip of Kamailio, hut in the tcpdump i see that Kamailio sends a 404.
Is there anything else needed yo be able to have users register on Kamailio and talk to each other, while Asterisk will handle all the media services such as voicemail, ivr, ...etc? In case one Asterisk goes down, the other one will handle the load.

**Comment by os11k** [comment] 2020-07-20 14:52
As far as this is not a bug and you got your kamailio running, I'm closing it. If you need any other help, just drop me an email. It is in my contacts.

**Closed as completed** 2020-07-20 14:53 UTC
